"using try/catch method to get a parameter that will make a certain output from a method in blank i wrote this code using try/catch, and i want it to output this: ..a null pointer exception occurred.in the finally block..the length of the string is 1.a number format exception occurred.in the finally block..a null pointer exception occurred.some type of exception occurred.in the finally block..the length of the string is 1.the value is 5...but for some reason when i call i try to call it from the main i get an error, so my question is how can i properly call the method from the main to get the output above?..this is the method i wrote:..public static void problem2(string s) {.    try {.        int stringlen = s.length();.        system.out.println(""the length of the string is "" + stringlen);.        int i = integer.parseint(s);.        system.out.println(""the value is "" + i);.    } catch (numberformatexception e1) {.        system.out.println(""a number format exception occurred"");.    } catch (nullpointerexception e2) {.        system.out.println(""a null pointer exception occurred"");.    } catch (exception e3) {.        system.out.println(""some type of exception occurred"");.    } finally {.        system.out.println(""in the finally block"");.    }.}"
