"join throws startswith error after using os.walk just a test script to loop to my entire home directory recursively. on my test server, the join command throws this strange error...  file ""print_idv3.py"", line 20, in &lt;module&gt;.listdirs(""/home/jelmer/"").  file ""print_idv3.py"", line 7, in listdirs.list_of_files=os.path.join(root,files). file ""/usr/lib/blank2.7/posixpath.py"", line 66, in join.if b.startswith('/'):.attributeerror: 'list' object has no attribute 'startswith'...the code is as follows. files and root are not empty at all, so it should work...def listdirs(dir):.    for root, subfolders,files in os.walk(dir,topdown=false):.            list_of_files=os.path.join(root,files).            print files.            print root.            return.    return..def main():.      #mainrunroutine.      return..if __name__==""__main__"":.    listdirs(""/home/jelmer/"")"
