"blank urllib2.urlopen returning 302 error even though page exists i am using the blank function urllib2.urlopen to read the http://www.bad.org.uk/ website but i keep getting a 302 error even though when i visit the site it loads ok.  anyone have any idea why?..import socket ..headers = { 'user-agent' : 'mozilla/4.0 (compatible; msie 5.5; windows nt)' }..socket.setdefaulttimeout(10)..try:.    req = urllib2.request('http://www.bad.org.uk/', none, headers).    urllib2.urlopen(req).    return true         # url exist.except valueerror, ex:.    print 'url: %s not well formatted' % 'http://www.bad.org.uk/'.    return false        # url not well formatted.except urllib2.httperror, ex:.    print 'the server couldn't fulfill the request for %s.' % 'http://www.bad.org.uk/'.    print 'error code: ', ex.code.    return false.except urllib2.urlerror, ex:.    print 'we failed to reach a server for %s.' % 'http://www.bad.org.uk/'.    print 'reason: ', ex.reason.    return false        # url don't seem to be alive...error printed:..the server couldn't fulfill the request for http://www.bad.org.uk//site/1/default.aspx..error code:  302"
