"single class. typeerror: 'module' object is not callable     def processfailuresignatures(self, directory, report_dir):.        for element in os.listdir(directory):.        full_path = os.path.join(directory, element).        m = re.match('(d+)_failed_pass(d+)_(.+)', element).        ........def gathertestresults(self):.    earliest =  time.time() - test_results_max_age_seconds..    for element in os.listdir(results_dir_path):.        time_struct = time.strptime(element, ""%y-%m-%d_%h-%m-%s"").        time_sse    = time.mktime(time_struct)..        outdir       = os.path.join(report_dir_path, self.accurev_info['basis'], self.rtl, element).        summary_file = os.path.join(results_dir_path, element, ""summary.txt"").        perf_file    = os.path.join(results_dir_path, element, ""performance_data.xml"")..        if os.path.isfile(perf_file) and not self.istestcomplete(perf_file, element):.           continue.        if(time_sse &gt; earliest):.            if os.path.isfile(perf_file):.                self.processtestperformance(perf_file, element)..            if os.path.isfile(summary_file):.                self.processtestsummary(summary_file, element)..            self.processfailuresignatures(os.path(results_dir_path, element), outdir).        ..............i get the following error, also when i type self.processfailuresignatures in blank window, the function name doesn't appear. i don't understand why this wont be in the scope of the class. as it is written under class above the calling function...file ""fbe_test_analyze.py"", line 621, in gathertestresults.    self.processfailuresignatures(os.path(results_dir_path, element), outdir).typeerror: 'module' object is not callable"
