"sending mail error blank i get the following error when trying a script thaat sends mail..    import urllib.request.    import re.    import smtplib.    from email.mime.text import mimetext.    from bs4 import beautifulsoup.    page=urllib.request.urlopen(""http://www.crummy.com/"").    soup=beautifulsoup(page).    v=soup.findall('a',href=re.compile('http://www.crummy.com/2012/07/24/0')).    for link in v:..      w=link.get('href')...    server = smtplib.smtp( ""smtp.gmail.com"", 587 ).    server.starttls().    server.login( 'xxxxxxxxxxx', 'xxxxxxx' ).    server.sendmail( 'xxxxxxxxx', 'xxxxxxxxx', ""bonus question is up"" )....  traceback (most recent call last):  file ""c:blank32bonus"", line 14,.  in   server = smtplib.smtp( ""smtp.gmail.com"", 587 )  file.  ""c:blank32libsmtplib.py"", line 259, in init   file.  ""c:blank32libsmtplib.py"", line 319, in connect.      self.sock = self._get_socket(host, port, self.timeout)   file ""c:blank32 libsmtplib.py"", line 294, in _get_socket.      return socket.create_connection((host, port), timeout)   file ""c:blank32libsocket.py"", line 386, in create_connection.      for res in getaddrinfo(host, port, 0, sock_stream): socket.gaierror: [errno 11004] getaddrinfo failed plse advice on the.  best way to go round it"
